current_dir := ${CURDIR}
TARGET := basys3
TOP := Patmos
SOURCES := $(wildcard ${CURDIR}/../../build/*.v)

# Include your constraint file path(s) below. Use either an XDC file
# or a PCF+SDC pair. Don't use all three file types.
#PCF := ${CURDIR}/basys3.pcf
#SDC := ${CURDIR}/basys3.sdc
XDC := ${CURDIR}/basys3.xdc

include common.mk
