current_dir := ${CURDIR}
TARGET := basys3
TOP := patmos_top
SOURCES := $(wildcard ${CURDIR}/../../build/*.v) ${CURDIR}/../../verilog/patmos_ocmem.v

# Include your constraint file path(s) below. Use either an XDC file
# or a PCF+SDC pair. Don't use all three file types.
PCF := ${CURDIR}/basys3.pcf
#SDC := ${CURDIR}/basys3.sdc


include common.mk
